import path from 'path';
import fs from 'fs';
import { parseArgs } from 'util';
import { checkEnv } from './index';
import { formatErrors, formatSuccess, colorize, C } from './reporter';
import type { EnvSchema, FieldSchema } from './types';

const VERSION = (() => {
  try {
    const pkgPath = path.resolve(__dirname, '../package.json');
    return (JSON.parse(fs.readFileSync(pkgPath, 'utf8')) as { version: string }).version;
  } catch { return '2.0.0'; }
})();

const HELP = `
Usage: env-validator <command> [options]

Commands:
  validate   Validate environment variables against a schema  [default]
  generate   Generate a .env.example file from a schema

Validate options:
  --schema=<path>     Path to schema file (.js)   [required]
  --env=<path>        .env file(s) to load         [default: .env]
  --strict            Warn on undeclared env vars
  --no-dotenv         Skip .env file loading
  --abort-early       Stop after first error
  --quiet             No output, exit code only
  --mode=<mode>       strict | warn | silent       [default: strict]

Generate options:
  --schema=<path>     Path to schema file (.js)   [required]
  --output=<path>     Output file path             [default: .env.example]

Global:
  --version           Print version
  --help              Show this help

Exit codes:
  0   Valid / generated successfully
  1   Validation errors found
  2   Bad arguments or schema load failure
`;

function loadSchema(schemaPath: string): EnvSchema {
  const resolved = path.resolve(process.cwd(), schemaPath);
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    let schema = require(resolved) as unknown;
    if (schema && typeof schema === 'object' && !Array.isArray(schema) &&
        'schema' in (schema as object)) {
      schema = (schema as Record<string, unknown>)['schema'];
    }
    if (typeof schema !== 'object' || schema === null || Array.isArray(schema)) {
      throw new Error('Schema file must export a plain object');
    }
    return schema as EnvSchema;
  } catch (err) {
    process.stderr.write(
      colorize(C.red, `Error: Cannot load schema from "${resolved}"\n`) +
      colorize(C.gray, `  ${(err as Error).message}\n`),
    );
    process.exit(2);
  }
}

// ── generate command ──────────────────────────────────────────────────────────
function runGenerate(schema: EnvSchema, outputPath: string): void {
  const lines: string[] = [
    `# .env.example — generated by env-validator`,
    `# Fill in the values below and rename to .env`,
    '',
  ];

  for (const [key, def] of Object.entries(schema)) {
    const d = def as FieldSchema;
    const isRequired = d.required !== false && d.default === undefined;
    const tag = isRequired ? ' [required]' : d.required === false ? ' [optional]' : '';

    lines.push(`# ${key}${tag}`);

    const typePart = d.type ? `Type: ${d.type}` : 'Type: string';
    const extras: string[] = [typePart];
    if (d.default !== undefined) extras.push(`Default: ${JSON.stringify(d.default)}`);
    if (d.enum)      extras.push(`Allowed: ${d.enum.join(', ')}`);
    if (d.min !== undefined)       extras.push(`min: ${d.min}`);
    if (d.max !== undefined)       extras.push(`max: ${d.max}`);
    if (d.minLength !== undefined) extras.push(`minLength: ${d.minLength}`);
    if (d.maxLength !== undefined) extras.push(`maxLength: ${d.maxLength}`);
    if (d.pattern)   extras.push(`pattern: ${d.pattern.toString()}`);
    lines.push(`# ${extras.join(' | ')}`);

    if (d.description) lines.push(`# Description: ${d.description}`);
    if (d.example)     lines.push(`# Example: ${d.example}`);

    if (!isRequired && d.default === undefined) {
      // Optional with no default — commented out
      lines.push(`# ${key}=`);
    } else if (d.default !== undefined) {
      lines.push(`${key}=${d.default}`);
    } else {
      lines.push(`${key}=`);
    }

    lines.push('');
  }

  const output = lines.join('\n');
  fs.writeFileSync(path.resolve(process.cwd(), outputPath), output, 'utf8');
  process.stdout.write(
    colorize(C.green, `✔  Generated ${outputPath} with ${Object.keys(schema).length} variable(s).\n`),
  );
}

// ── validate command ──────────────────────────────────────────────────────────
function runValidate(
  schema: EnvSchema,
  args: {
    env?: string;
    noDotenv: boolean;
    strict: boolean;
    abortEarly: boolean;
    quiet: boolean;
    mode?: string;
  },
): void {
  const validateOptions: Parameters<typeof checkEnv>[1] = {
    strict:     args.strict,
    abortEarly: args.abortEarly,
    quiet:      true,
  };

  if (!args.noDotenv) {
    validateOptions.dotenv = args.env ?? true;
  }

  let result: ReturnType<typeof checkEnv>;
  try {
    result = checkEnv(schema, validateOptions);
  } catch (err) {
    process.stderr.write(colorize(C.red, `Error: ${(err as Error).message}\n`));
    process.exit(2);
  }

  const { errors, valid } = result;

  if (!args.quiet) {
    if (errors.length > 0) {
      process.stderr.write(
        formatErrors(errors, valid ? 'Environment Warnings' : 'Environment Validation Failed'),
      );
    }
    if (valid) {
      process.stdout.write(formatSuccess(Object.keys(schema).length));
      const warnings = errors.filter(e => e.severity === 'warning');
      if (warnings.length > 0) {
        process.stdout.write(
          colorize(C.yellow, `  ${warnings.length} warning(s) shown above.\n\n`),
        );
      }
    }
  }

  process.exit(valid ? 0 : 1);
}

// ── Main ─────────────────────────────────────────────────────────────────────
async function main(): Promise<void> {
  const rawArgs = process.argv.slice(2);

  // Detect subcommand
  let command = 'validate';
  let args = rawArgs;
  if (rawArgs[0] === 'validate' || rawArgs[0] === 'generate') {
    command = rawArgs[0];
    args = rawArgs.slice(1);
  }

  let values: Record<string, unknown>;
  try {
    ({ values } = parseArgs({
      args,
      options: {
        schema:        { type: 'string'  },
        env:           { type: 'string'  },
        output:        { type: 'string'  },
        strict:        { type: 'boolean', default: false },
        'no-dotenv':   { type: 'boolean', default: false },
        'abort-early': { type: 'boolean', default: false },
        quiet:         { type: 'boolean', default: false },
        mode:          { type: 'string'  },
        version:       { type: 'boolean', default: false },
        help:          { type: 'boolean', default: false },
      },
      allowPositionals: false,
      strict: true,
    }));
  } catch (err) {
    process.stderr.write(colorize(C.red, `Error: ${(err as Error).message}\n`));
    process.exit(2);
  }

  if (values['help']) { process.stdout.write(HELP); process.exit(0); }
  if (values['version']) { process.stdout.write(`env-validator v${VERSION}\n`); process.exit(0); }

  if (!values['schema']) {
    process.stderr.write(colorize(C.red, 'Error: --schema=<path> is required\n'));
    process.exit(2);
  }

  const schema = loadSchema(values['schema'] as string);

  if (command === 'generate') {
    runGenerate(schema, (values['output'] as string | undefined) ?? '.env.example');
    return;
  }

  runValidate(schema, {
    env:        values['env'] as string | undefined,
    noDotenv:   values['no-dotenv'] as boolean,
    strict:     values['strict'] as boolean,
    abortEarly: values['abort-early'] as boolean,
    quiet:      values['quiet'] as boolean,
    mode:       values['mode'] as string | undefined,
  });
}

main().catch(err => {
  process.stderr.write(`Unexpected error: ${(err as Error).message}\n`);
  process.exit(2);
});
